TestPriceList/Controllers/PriceListController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using TestPriceList.Data;
using TestPriceList.Models;
using TestPriceList.ViewModels;

namespace TestPriceList.Controllers
{
    public class PriceListController : Controller
    {
        private readonly Db db;

        public PriceListController(Db _db)
        {
            db = _db;
        }

        public IActionResult Index(List<PriceList> pricesList) 
        {
            pricesList = db.PricesList.ToList();
            return View(pricesList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(PriceListViewModel model, int? id)
        {
            if (ModelState.IsValid)
            {
                var priceList = new PriceList
                {
                    Name = model.Name
                };
                db.PricesList.Add(priceList);
                db.SaveChanges();               
                if (model.Columns != null)
                {
                    var columns = new List<Column>();
                    foreach (var columnViewModel in model.Columns)
                    {
                        var column = new Column
                        {
                            Name = columnViewModel.Name,
                            Types = columnViewModel.Types,
                            PriceListId = priceList.Id
                        };
                        columns.Add(column);
                    }
                    db.Columns.AddRange(columns);
                    db.SaveChanges();
                }
                id = priceList.Id;
                ViewBag.PriceListId = priceList.Name;
                return RedirectToAction("Create", "Tovars", new {id});
            }
            return View(model);
        }
    }
}

TestPriceList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestPriceList</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestPriceList.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="PriceList" asp-action="Index">Прайсы</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TestPriceList 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>